### ISSUE TITLE
another awesome-robotics list

### ISSUE THREAD

**Issue by ahundt** [Kiloreux/awesome-robotics#21]
Found your list and added it to my own, which is a bit more software focused https://github.com/ahundt/awesome-robotics, also found https://github.com/jslee02/awesome-robotics-libraries.

**Comment by Kiloreux** [comment]
Alright, That looks like a great list @ahundt. Not sure what I am expected to do here? But will be happy to help in any way.

**Comment by ahundt** [comment]
Just an FYI in case you found them worth adding to your other awesome lists.

**Comment by Kiloreux** [comment]
@ahundt I have committed the mentions lists to the list. Thank you.
