### ISSUE TITLE
Robotic Slack Group no longer active

### ISSUE THREAD

**Issue by mateusbs17** [kiloreux/awesome-robotics#24]
I tried to enter the robot slack team, but it happens the group has been deleted.

I am not sure if there is another one, but, if not, the link should be deleted from the documentation.

**Comment by dignakov** [comment]
There's a robotics discord  group: https://discord.gg/C37Ph9Q

It's pretty new (like 2 weeks) so a little small for now, but it's off to a good start.

**Comment by kiloreux** [comment]
Hey @mateusbs17 I just deleted the tag to it. Thank you for pointing it out. Much appreciated
