### ISSUE TITLE
Robotics Companies

### ISSUE THREAD

**Issue by paraschas** [Kiloreux/awesome-robotics#4]
Hey @Kiloreux , would you like me to add a "Robotics Companies" section in the list for some big and important robotics companies? Some that come to mind are ABB, KUKA, FANUC, Rethink Robotics and iRobot.

**Comment by Kiloreux** [comment]
Hey @paraschas , That'd be really cool for robotics job seekers and who want to buy robots, Thanks , please don't hesitate to add anything else you want to.

**Comment by Kiloreux** [comment]
I'll be closing this issue now, please feel free to ask any other questions here or open a new issue.
